server:
  port: 8018
#  servlet:
#    session:
#      timeout: 10

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://####:3306/security?useUnicode=true&characterEncoding=utf-8
    username: ####
    password: ####
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
